name: CI
on:
    push:
        branches:
        - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: pnpm/action-setup@v2
          with:
            version: latest
        - uses: actions/setup-node@v2
          with:
            node-version: '18.x'
            cache: 'pnpm'
        - run: pnpm install --frozen-lockfile
        - run: pnpm run build