name: Reference Map Publish
on:
    push:
        branches:
        - 'develop'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: pnpm/action-setup@v2
          with:
            version: latest
        - uses: actions/setup-node@v3
          with:
            node-version: '18.x'
            cache: 'pnpm'
        - run: pnpm install --frozen-lockfile
        - run: pnpm run lint
        - name: Create Publish Pull Request
          id: changesets
          uses: changesets/action@v1
          with:
            # this expects you to have a npm script called version that runs some logic and then calls `changeset version`.
            version: pnpm version
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}